package ReportGenerator {
    use v5.36;

    sub new($class) {
        return bless {}, $class;
    }

    sub generate($self, $format, $data) {
        my $output = '';

        # タイトル生成
        if ($format eq 'pdf') {
            $output .= "\\textbf{\\Large " . $data->{title} . "}\n\n";
        } elsif ($format eq 'html') {
            $output .= "<h1>" . $data->{title} . "</h1>\n";
        } elsif ($format eq 'markdown') {
            $output .= "# " . $data->{title} . "\n\n";
        }

        # テーブル生成
        if ($format eq 'pdf') {
            $output .= "\\begin{tabular}{|" . join('|', map { "c" } $data->{rows}->[0]->@*) . "|}\n";
            for my $row ($data->{rows}->@*) {
                $output .= join(' & ', $row->@*) . " \\\\\n";
            }
            $output .= "\\end{tabular}\n\n";
        } elsif ($format eq 'html') {
            $output .= "<table>\n";
            for my $row ($data->{rows}->@*) {
                $output .= "<tr>" . join('', map { "<td>$_</td>" } $row->@*) . "</tr>\n";
            }
            $output .= "</table>\n";
        } elsif ($format eq 'markdown') {
            my $first = 1;
            for my $row ($data->{rows}->@*) {
                $output .= "| " . join(' | ', $row->@*) . " |\n";
                if ($first) {
                    $output .= "| " . join(' | ', map { "---" } $row->@*) . " |\n";
                    $first = 0;
                }
            }
            $output .= "\n";
        }

        # フッター生成
        # BUG: $format のチェックが甘く、3フォーマット目で混乱が起きやすい構造
        # ※ 実際のバグ: markdown追加時に条件分岐の順序を間違え、
        #   markdown指定時にhtml用フッターが混入する
        if ($format eq 'pdf') {
            $output .= "\\vfill\n\\footnotesize Generated by ReportSystem\n";
        } elsif ($format eq 'html') {
            $output .= "<footer><small>Generated by ReportSystem</small></footer>\n";
        } elsif ($format eq 'markdwon') {  # ← typo! 'markdwon' (スペルミス)
            $output .= "\n---\n*Generated by ReportSystem*\n";
        }
        # markdownがtypoで引っかからず、フッターが欠落する

        return $output;
    }
}

1;
