package Report::Html::Footer {
    use v5.36;
    use Moo;
    with 'Role::ReportFooter';

    sub render($self) {
        return "<footer><small>Generated by ReportSystem</small></footer>\n";
    }
}

1;
