#!/usr/bin/env perl
use v5.36;
use Test::More;
use lib 'lib';
use ReportGenerator;

my $data = {
    title => 'Monthly Sales Report',
    rows  => [
        ['Product', 'Sales', 'Revenue'],
        ['Widget A', '100', '$5,000'],
        ['Widget B', '200', '$12,000'],
    ],
};

subtest 'PDF generation' => sub {
    my $gen = ReportGenerator->new;
    my $out = $gen->generate('pdf', $data);
    like($out, qr/\\textbf/, 'PDF title uses LaTeX bold');
    like($out, qr/\\begin\{tabular\}/, 'PDF table uses tabular');
    like($out, qr/Generated by ReportSystem/, 'PDF footer present');
};

subtest 'HTML generation' => sub {
    my $gen = ReportGenerator->new;
    my $out = $gen->generate('html', $data);
    like($out, qr/<h1>/, 'HTML title uses h1');
    like($out, qr/<table>/, 'HTML table present');
    like($out, qr/<footer>/, 'HTML footer present');
};

subtest 'Markdown generation' => sub {
    my $gen = ReportGenerator->new;
    my $out = $gen->generate('markdown', $data);
    like($out, qr/^# /m, 'Markdown title uses # heading');
    like($out, qr/\|/, 'Markdown table uses pipe');
    # このテストが失敗する！ typo で markdown フッターが出力されない
    like($out, qr/Generated by ReportSystem/, 'Markdown footer present');
};

subtest 'unknown format returns empty-ish' => sub {
    my $gen = ReportGenerator->new;
    my $out = $gen->generate('unknown', $data);
    is($out, '', 'unknown format returns empty string');
};

done_testing;
