#!/usr/bin/env perl
use v5.36;
use Test::More;
use lib 'lib';

use ReportGenerator;
use ReportFactory::Pdf;
use ReportFactory::Html;
use ReportFactory::Markdown;

my $data = {
    title => 'Monthly Sales Report',
    rows  => [
        ['Product', 'Sales', 'Revenue'],
        ['Widget A', '100', '$5,000'],
        ['Widget B', '200', '$12,000'],
    ],
};

subtest 'PDF generation via factory' => sub {
    my $gen = ReportGenerator->new(factory => ReportFactory::Pdf->new);
    my $out = $gen->generate($data);
    like($out, qr/\\textbf/, 'PDF title uses LaTeX bold');
    like($out, qr/\\begin\{tabular\}/, 'PDF table uses tabular');
    like($out, qr/Generated by ReportSystem/, 'PDF footer present');
    unlike($out, qr/<h1>/, 'No HTML contamination in PDF');
    unlike($out, qr/^# /m, 'No Markdown contamination in PDF');
};

subtest 'HTML generation via factory' => sub {
    my $gen = ReportGenerator->new(factory => ReportFactory::Html->new);
    my $out = $gen->generate($data);
    like($out, qr/<h1>/, 'HTML title uses h1');
    like($out, qr/<table>/, 'HTML table present');
    like($out, qr/<footer>/, 'HTML footer present');
    unlike($out, qr/\\textbf/, 'No PDF contamination in HTML');
    unlike($out, qr/^# /m, 'No Markdown contamination in HTML');
};

subtest 'Markdown generation via factory' => sub {
    my $gen = ReportGenerator->new(factory => ReportFactory::Markdown->new);
    my $out = $gen->generate($data);
    like($out, qr/^# /m, 'Markdown title uses # heading');
    like($out, qr/\|/, 'Markdown table uses pipe');
    like($out, qr/Generated by ReportSystem/, 'Markdown footer present');
    unlike($out, qr/<h1>/, 'No HTML contamination in Markdown');
    unlike($out, qr/\\textbf/, 'No PDF contamination in Markdown');
};

subtest 'factory guarantees family consistency' => sub {
    # Factory Role requires create_title, create_table, create_footer
    # A factory that forgets one will fail at compile time
    my $pdf_factory = ReportFactory::Pdf->new;
    ok($pdf_factory->does('Role::ReportFactory'), 'PDF factory implements Role::ReportFactory');

    my $html_factory = ReportFactory::Html->new;
    ok($html_factory->does('Role::ReportFactory'), 'HTML factory implements Role::ReportFactory');

    my $md_factory = ReportFactory::Markdown->new;
    ok($md_factory->does('Role::ReportFactory'), 'Markdown factory implements Role::ReportFactory');
};

subtest 'components implement their roles' => sub {
    my $factory = ReportFactory::Pdf->new;
    ok($factory->create_title->does('Role::ReportTitle'), 'PDF title does Role::ReportTitle');
    ok($factory->create_table->does('Role::ReportTable'), 'PDF table does Role::ReportTable');
    ok($factory->create_footer->does('Role::ReportFooter'), 'PDF footer does Role::ReportFooter');
};

done_testing;
